"""init

Revision ID: 2643cfd0a6a8
Revises: 2c9633954024
Create Date: 2025-05-21 18:53:06.148367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2643cfd0a6a8'
down_revision: Union[str, None] = '2c9633954024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('feedback_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'feedback', ['feedback_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'feedback_id')
    # ### end Alembic commands ###
