"""init

Revision ID: 7de21e4b6524
Revises: ed5a2bc9c9ea
Create Date: 2025-05-21 18:27:58.472837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de21e4b6524'
down_revision: Union[str, None] = 'ed5a2bc9c9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_files_id', table_name='media_files')
    op.drop_table('media_files')
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.create_table('media_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], name='media_files_feedback_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='media_files_pkey')
    )
    op.create_index('ix_media_files_id', 'media_files', ['id'], unique=False)
    # ### end Alembic commands ###
