"""init

Revision ID: 8cdf21fa4e51
Revises: 730af25247b4
Create Date: 2025-05-21 19:00:09.809025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdf21fa4e51'
down_revision: Union[str, None] = '730af25247b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_feedback_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'feedback_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('feedback_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_feedback_id_fkey', 'products', 'feedback', ['feedback_id'], ['id'])
    # ### end Alembic commands ###
